export const academyTheme = {
  colors: {
    background: '#F2F7FB',
    backgroundSoft: '#F8FCFF',
    ink: '#102B3A',
    inkMuted: '#4F6678',
    inkFaint: '#728697',
    green: '#2F7D6B',
    greenSoft: '#E1F4F1',
    greenDeep: '#1C5F55',
    sky: '#2F80C9',
    skySoft: '#E5F2FF',
    amber: '#C77D12',
    amberSoft: '#FFF0CF',
    clay: '#B36F64',
    line: '#D5E2EA',
    white: '#FFFFFF',
  },
  radius: {
    panel: 8,
    pill: 999,
  },
  shadow: {
    elevation: 2,
    shadowColor: '#2A4A60',
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
} as const;
