replicaCount: 1

image:
  repository: ghcr.io/hazyforge/hazyforge-academy
  pullPolicy: IfNotPresent
  tag: "master"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80
  containerPort: 80

resources:
  requests:
    cpu: 25m
    memory: 96Mi
  limits:
    cpu: 300m
    memory: 256Mi

env:
  ACADEMY_API_ALLOWED_ORIGINS: "https://learn.hazyforge.io"
  ACADEMY_AUTH_ISSUER: "https://hazyforge1-azsbgb.us1.zitadel.cloud"
  ACADEMY_AUTH_AUDIENCES: ""
  ACADEMY_AUTH_CLOCK_TOLERANCE_SECONDS: "60"
  CAL_API_BASE_URL: "https://cal.hazyforge.io/api"
  ACADEMY_CAL_USERNAME: "palehazy"
  ACADEMY_CAL_EVENT_TYPE_SLUG: "30min"
  ACADEMY_CAL_TIME_ZONE: "America/Chicago"
  CAL_SLOTS_API_VERSION: "2024-09-04"
  CAL_BOOKINGS_API_VERSION: "2026-02-25"

envFromSecrets: []

livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /healthz
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
